{
 "title": "danswer-grafana-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Namespace total - namespace: \"default\" ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"default\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_usage_bytes{namespace=\"default\"} / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total[10m]) * 8 / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network incoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[10m]) * 8 / 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cpu core per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[15m])) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\"}) by (pod) / 1024^2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}